### ISSUE TITLE
Vim detects error for vim-pandoc-after when working with vim-table-mode

### ISSUE THREAD

**Issue by mhminai** [vim-pandoc/vim-pandoc-after#4]
When I open a GVim window on a pandoc formatted file with:

```
let g:pandoc#after#modules#enabled = ["supertab", "ultisnips", "vim-table-mode"]
```

I get the following error:

```
Error detected while processing function pandoc#after#Init:
Line 3:
E107: Missing parentheses: pandoc#after#vim-table-mode#Init()
```

Not sure if this is due to vim-table-mode plugin or vim-pandoc-after, but thought I would place it here as the error comes only when I enable the module for vim-pandoc-after

This could possibly be because vim-table-mode does not have an Init() function? I guess at the minimum the readme at vim-pandoc-after should be modified

**Comment by Anthony-Fiddes** [comment]
EDIT: Actually, as soon as I asked, I figured it out. I have to put tablemode instead of vim-table-mode, and the required strings are right next to the plugins in the README. Thank you!

I'm sorry to necro this, but I'm a new vim user and I was wondering: where could I find this documentation?
